name: Metrics
on:
  # 每天北京时间早 8 点自动更新
  schedule: [{cron: "0 0 * * *"}]
  # 支持手动触发更新
  workflow_dispatch:
  # 每次你推送到主分支时也更新
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 这里的 TOKEN 名字必须和你之前在 Settings 里设置的一致
          token: ${{ secrets.METRICS_TOKEN }}
          
          # 核心设置：只开启语言统计插件
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex # 忽略掉这些非核心编程语言
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes # 深度分析（更准确）
          
          # 存储位置（生成到仓库根目录）
          filename: github-metrics.svg
